swagger: "2.0"
info:
  description: "This is the documentation of our API. We explain the existing routes you can use in your application. There is a description for Film , Showing , Actor and Director."
  version: "1.0.0"
  title: "API Cinema"

paths:

  /films/{id}:
    get:
      tags:
      - "film"
      summary: "Return a film"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of film to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Film"
  /films/search:
    get:
      tags:
      - "film"
      summary: "Return a list of films"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "filter research"
        description: "filter request"
        schema:
          $ref: "#/definitions/FilmFilter"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Film"


  /directors/{id}:
    get:
        tags:
        - "directors"
        summary: "Return informations about a director"
        description: ""
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - name: "id"
          in: "path"
          description: "ID of director"
          required: true
          type: "integer"
          format: "int64"
        responses:
          200:
            description: "successful operation"
            schema:
              $ref: "#/definitions/Director"

  /directors:
    get:
        tags:
        - "directors"
        summary: "Return list of director"
        description: ""
        consumes:
        - "application/json"
        produces:
        - "application/json"
        responses:
          200:
            description: "successful operation"
            schema:
              $ref: "#/definitions/Director"


  /actors/{id}:
    get:
        tags:
        - "actors"
        summary: "Return informations about a actor"
        description: ""
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - name: "id"
          in: "path"
          description: "ID of director"
          required: true
          type: "integer"
          format: "int64"
        responses:
          200:
            description: "successful operation"
            schema:
              $ref: "#/definitions/Actor"

  /actors:
    get:
        tags:
        - "actors"
        summary: "Return list of actor"
        description: ""
        consumes:
        - "application/json"
        produces:
        - "application/json"
        responses:
          200:
            description: "successful operation"
            schema:
              $ref: "#/definitions/Actor"

  /showings/search/{param}:
    get:
      tags:
      - "showings"
      summary: "Return informations about a showing"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "param"
        in: "path"
        description: "ID of film to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Showing"


definitions:

  Film:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        format: "string"
      releaseDate:
        $ref: "#/definitions/Date"
      synopsis:
        type: "string"
        format: "string"
      director:
        type: "integer"
        format: "int64"
      created_at:
        $ref: "#/definitions/Date"
      updated_at:
        $ref: "#/definitions/Date"
      director_data:
        type: "object"
        format: "array"
  Date:
    properties:
      date:
        type: "string"
        format: "date-time"
      timezone_type:
        type: "integer"
        format: "int"
      timezone:
        type: "string"
        format: "string"

  FilmFilter:
    properties:
      title:
        type: "string"
        format: "string"
      releaseDate:
        type: "string"
        format: "date"
      category:
        type: "string"
        format: "string"
      actorFirstname:
        type: "string"
        format: "string"
      actorLastname:
        type: "string"
        format: "string"
      directorLastname:
        type: "string"
        format: "string"
      directorFirstname:
        type: "string"
        format: "string"

  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Category"

  Director:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstname:
          type: "string"
          format: "string"
      lastname:
          type: "string"
          format: "string"
      nationality:
          type: "string"
          format: "string"
      birthday:
           $ref: "#/definitions/Date"
      biography:
          type: "string"
          format: "string"
    xml:
      name: "Director"

  Actor:
       type: "object"
       properties:
         id:
           type: "integer"
           format: "int64"
         firstname:
             type: "string"
             format: "string"
         lastname:
             type: "string"
             format: "string"
         nationality:
             type: "string"
             format: "string"
         birthday:
              $ref: "#/definitions/Date"
         biography:
             type: "string"
             format: "string"
       xml:
         name: "Actor"



  Showing:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        language_showing:
          type: "integer"
          format: "int64"
        schedule:
          $ref: "#/definitions/Time"
        day:
          $ref: "#/definitions/Date"
        cinema:
          type: "integer"
          format: "int64"
        created_at:
          $ref: "#/definitions/Date"
        updated_at:
          $ref: "#/definitions/Date"

  Time:
      type: "object"
      properties:
            hour:
              type: "string"
              format: "int64"
            minutes:
              type: "string"
              format: "int64"
            second:
              type: "string"
              format: "int64"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
